# Makefile for generating code from proto files

# Определяем цель 'generate' (аналог задачи 'gen' в Taskfile)
.PHONY: generate

generate: ## Generate code from proto files
	@protoc -I proto proto/sso/*.proto \
		--go_out=./gen/go/ \
		--go_opt=paths=source_relative \
		--go-grpc_out=./gen/go/ \
		--go-grpc_opt=paths=source_relative

# Определяем псевдоним 'gen' для вызова 'generate'
gen: generate
